//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public int Id { get; set; }
        public Nullable<int> vc_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> insertionDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public string status { get; set; }
        public Nullable<int> count_id { get; set; }
        public Nullable<decimal> summ { get; set; }
        public Nullable<int> material_id { get; set; }
        public string sender { get; set; }
        public string operation_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> withdrawamount { get; set; }
        public Nullable<int> Delivery_id { get; set; }
    
        public virtual COUNT COUNT { get; set; }
        public virtual materials materials { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual cards cards { get; set; }
        public virtual Delivery Delivery { get; set; }
    }
}
