//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cards()
        {
            this.application = new HashSet<application>();
            this.CARD_CLAIMS = new HashSet<CARD_CLAIMS>();
            this.favorite = new HashSet<favorite>();
        }
    
        public int Id { get; set; }
        public Nullable<int> layout_id { get; set; }
        public string text { get; set; }
        public string preview { get; set; }
        public string USER_ID { get; set; }
        public bool published { get; set; }
        public Nullable<int> ITEM_TYPE_ID { get; set; }
        public string preview_2 { get; set; }
        public int Images_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<application> application { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD_CLAIMS> CARD_CLAIMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite> favorite { get; set; }
        public virtual ITEM_TYPE ITEM_TYPE { get; set; }
        public virtual layout layout { get; set; }
        public virtual IMAGES IMAGES { get; set; }
    }
}
