//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COUNT()
        {
            this.application = new HashSet<application>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ITEM_TYPE_ID { get; set; }
        public Nullable<int> COUNT_VALUE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<application> application { get; set; }
        public virtual ITEM_TYPE ITEM_TYPE { get; set; }
    }
}
