//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class elements
    {
        public int Id { get; set; }
        public string path { get; set; }
        public int type_name_id { get; set; }
        public int item_type_id { get; set; }
        public Nullable<int> item_layout_id { get; set; }
    
        public virtual ELEMENTS_TYPES ELEMENTS_TYPES { get; set; }
        public virtual ITEM_TYPE ITEM_TYPE { get; set; }
        public virtual layout layout { get; set; }
    }
}
