//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<application> application { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CARD_CLAIMS> CARD_CLAIMS { get; set; }
        public virtual DbSet<cards> cards { get; set; }
        public virtual DbSet<COUNT> COUNT { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<elements> elements { get; set; }
        public virtual DbSet<ELEMENTS_TYPES> ELEMENTS_TYPES { get; set; }
        public virtual DbSet<favorite> favorite { get; set; }
        public virtual DbSet<ITEM_TYPE> ITEM_TYPE { get; set; }
        public virtual DbSet<layout> layout { get; set; }
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<Towns> Towns { get; set; }
        public virtual DbSet<IMAGES> IMAGES { get; set; }
    }
}
